jobs:
  lint_knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: ./.github/actions/prepare
      - run: npm run lint:knip

name: Lint Knip

on:
  pull_request: ~
  push:
    branches:
      - main
